.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH qrrs 1  "qrrs 0.1.11" 
.SH NAME
qrrs \- CLI QR code generator and reader
.SH SYNOPSIS
\fBqrrs\fR [\fB\-r\fR|\fB\-\-read\fR] [\fB\-t\fR|\fB\-\-terminal\fR] [\fB\-o\fR|\fB\-\-output\-format\fR] [\fB\-m\fR|\fB\-\-margin\fR] [\fB\-i\fR|\fB\-\-invert_colors\fR] [\fB\-\-generate\-completions\fR] [\fB\-e\fR|\fB\-\-error\-correction\-level\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIINPUT\fR] [\fIOUTPUT\fR] 
.SH DESCRIPTION
CLI QR code generator and reader
.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-read\fR
Read the qrcode instead of generating it
.TP
\fB\-t\fR, \fB\-\-terminal\fR
Display code in terminal
.TP
\fB\-o\fR, \fB\-\-output\-format\fR=\fIFORMAT\fR [default: image]
Format in which the qrcode will be saved
.br

.br
[\fIpossible values: \fRimage, svg, unicode]
.TP
\fB\-m\fR, \fB\-\-margin\fR=\fImargin\fR [default: 5]
Margin applied to qrcode
.TP
\fB\-i\fR, \fB\-\-invert_colors\fR
Invert qrcode colors
.TP
\fB\-\-generate\-completions\fR=\fISHELL\fR
Generate completion file for the specified shell
.br

.br
[\fIpossible values: \fRbash, elvish, fish, powershell, zsh]
.TP
\fB\-e\fR, \fB\-\-error\-correction\-level\fR=\fILEVEL\fR [default: medium]
Error correction level for the QR code
.br

.br
[\fIpossible values: \fRlow, l, medium, m, quartile, q, high, h]
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fIINPUT\fR]
Input data
.TP
[\fIOUTPUT\fR]
Output file
.SH EXTRA

Examples:
  qrrs "Some text"
  qrrs "Some text" /tmp/qr.png

  qrrs \-\-read /tmp/qr.png
  Some text

  qrrs \-\-read /tmp/qr.png /tmp/qr1.png
  qrrs \-\-read /tmp/qr1.png
  Some text
.SH VERSION
v0.1.11
.SH AUTHORS
Lenivaya <danylo.osipchuk@proton.me>
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH "EXAMPLES OF USAGE"
qrrs "Your input here"
.br
qrrs "Something" /tmp/qr.png 
.br
qrrs \-r /tmp/qr.png 
.br

